FROM openjdk:17
EXPOSE 8080
ADD target/SpringBoot-Jenkins-Docker-integration-demo.jar SpringBoot-Jenkins-Docker-integration-demo.jar
ENTRYPOINT ["java", "-jar", "/SpringBoot-Jenkins-Docker-integration-demo.jar"]